### PR TITLE
Adding emoji to README

### PR DESCRIPTION
**Pull request by gwaygenomics**
:smirk_cat: Inspiration from [this twitter thread](https://twitter.com/GreeneScientist/status/895384467086479360).

### CODE REVIEW

**Comment by gwaygenomics** [comment]
also possible reviewer: @michaelmhoffman

**Comment by cgreene** [comment]
I'm amazed this works. I think you need @michaelmhoffman to approve to merge it. :smirk_cat:

**Comment by michaelmhoffman** [comment]
Only approving if you give me co-authorship on the paper. Pretty sure my contribution satisfies all the ICMJE requirements.

**Comment by michaelmhoffman** [comment]
Just kidding. Approved with gusto. 👍

**Pull request merged**
